language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update && composer install

script: vendor/bin/kahlan --config=kahlan-config.travis.php

after_success:
    - "if [ $(phpenv version-name) = '5.6' ]; then curl -X POST -d @codeclimate.json -H 'Content-Type:application/json' https://codeclimate.com/test_reports --verbose; fi"

env:
    global:
        - secure: "NxZ9yClukWFx+dmZrfN8IacsQWteRC84xljI1Wy7YzA9vBX24RuO4ahsAFTr21XMFlNG6iZ0MNC2CJiSudm0Ki/+e2iPoTN17U3Hzr0z2zia3rTlWnCusaABOx7z6rL1rvm4GsnCO6KOl3ZgKm3tSNFKyIosqr06jwZQf+sNnc0="
matrix:
    allow_failures:
        - php: hhvm
